packaging_format = 2

id = "snappymail"
name = "SnappyMail"
description.en = "Simple, modern, lightweight & fast web-based e-mail client"
description.fr = "Client de messagerie Web simple, moderne, léger et rapide"

version = "2.37.3~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://snappymail.eu/"
demo = "https://snappymail.eu/demo/"
admindoc = "https://github.com/the-djmaze/snappymail/wiki"
code = "https://github.com/the-djmaze/snappymail"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = true

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/snappymail"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/the-djmaze/snappymail/releases/download/v2.37.3/snappymail-2.37.3.tar.gz"
        sha256 = "15ae956d63d13a47554bcc07917602351f8388147a4aabdf9ab8c65658619305"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "^snappymail-[0-9\\.\\-]*tar.gz$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "php8.3-uuid",
        "php8.3-imagick",
        "php8.3-sqlite3",
        "php8.3-tidy",
        "php8.3-dom",
        "php8.3-intl",
        "php8.3-mysql",
        "php8.3-curl",
        "php8.3-gd",
        "php8.3-cli",
        "php8.3-xml",
        "php8.3-mbstring",
        "php8.3-ldap",
    ]

    [resources.database]
    type = "mysql"
