test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.3c1a929c.name = "Upgrade from 2.16.1"
